services:
    run_with_valgrind:
        hostname: valgrind-binary-runner
        container_name: valgrind-binary-runner

        build:
            context: .
            dockerfile: Dockerfile
        image: valgrind_image:latest

        env_file:
            - .env
        environment:
            # Lista de paquetes a instalar en tiempo de ejecución (separados por espacio)
            REQUIRED_PACKAGES: ""
            # Argumentos de Valgrind (por ejemplo: "--leak-check=full --show-leak-kinds=all")
            VALGRIND_ARGS: "--leak-check=full"
            # Nombre del binario a ejecutar dentro de /valgrinduser/app
            BINARY_NAME: ${BINARY_NAME}
            # Ejecutar como root si se setea a "true", de lo contrario ejecuta como 1000:1000
            ROOT_ACCESS: "false"

        volumes:
            # Montar la carpeta local de la aplicación en modo solo lectura
            # Sustituye /ruta/local/tu_app por la ruta real
            - ${BINARY_FOLDER}:/valgrinduser/app
        tty: true
        restart: none
